export const SET_SONG_TYPE_LIST = 'SET_SONG_TYPE_LIST'

export const SET_SONG_TYPE_NAME = 'SET_SONG_TYPE_NAME'

export const SET_SONGS_LIST = 'SET_SONGS_LIST'

export const SET_CLASSIFY_LIST = 'SET_CLASSIFY_LIST'

export const SET_PLAY_MODE = 'SET_PLAY_MODE'

export const SET_PLAYING_STATE = 'SET_PLAYING_STATE'

export const SET_USER = 'SET_USER'

export const SET_MOVIE = 'SET_MOVIE'

export const SET_SEARCH_HISTORY = 'SET_SEARCH_HISTORY'

export const SET_PLAY_HISTORY = 'SET_PLAY_HISTORY'

export const SET_FAVORITE_LIST = 'SET_FAVORITE_LIST'
